# Generated by Django 5.0.6 on 2024-06-29 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(db_column='idProducto', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.AutoField(db_column='idCarrito', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('idProducto', models.ForeignKey(db_column='idProducto', default=1, on_delete=django.db.models.deletion.CASCADE, to='Libros.producto')),
            ],
        ),
    ]
