# Generated by Django 5.0.6 on 2024-06-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0003_remove_producto_id_producto_idproducto_carrito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['idProducto']},
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='idCarrito',
        ),
        migrations.AddField(
            model_name='carrito',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
