# Generated by Django 5.0.6 on 2024-06-29 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0004_alter_producto_options_remove_carrito_idcarrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Libros.producto'),
            preserve_default=False,
        ),
    ]
