# Generated by Django 5.0.6 on 2024-06-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0005_remove_carrito_idproducto_carrito_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
