# Generated by Django 5.0.6 on 2024-06-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0006_alter_carrito_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
