# Generated by Django 5.0.6 on 2024-06-30 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0008_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', default=1, on_delete=django.db.models.deletion.CASCADE, to='Libros.producto'),
            preserve_default=False,
        ),
    ]
